# DVC pipeline configuration
# This file defines the ML pipeline stages for reproducibility

# Example stages (customize based on your workflow):

stages:
  prepare_data:
    cmd: python scripts/prepare_data.py
    deps:
      - data/raw
      - scripts/prepare_data.py
    outs:
      - data/processed/market_data.parquet

  train_model:
    cmd: python scripts/train_model.py
    deps:
      - data/processed/market_data.parquet
      - scripts/train_model.py
    params:
      - train.learning_rate
      - train.batch_size
    outs:
      - data/models/strategy_model.pkl
    metrics:
      - metrics.json:
          cache: false

  evaluate:
    cmd: python scripts/evaluate.py
    deps:
      - data/models/strategy_model.pkl
      - data/processed/test_data.parquet
      - scripts/evaluate.py
    metrics:
      - evaluation_metrics.json:
          cache: false
