"""
Pydantic models for data validation and serialization.

These models ensure type safety throughout the application and
provide automatic validation of data from external sources.
"""

from pydantic import BaseModel, Field, validator
from typing import Optional, Dict, List, Any
from datetime import datetime
from enum import Enum


class SignalType(str, Enum):
    """Types of trading signals."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class OrderSide(str, Enum):
    """Order side for trades."""
    BUY = "buy"
    SELL = "sell"


class OrderStatus(str, Enum):
    """Status of trade orders."""
    PENDING = "pending"
    FILLED = "filled"
    PARTIAL = "partial"
    CANCELLED = "cancelled"
    REJECTED = "rejected"


class MarketDataType(str, Enum):
    """Types of market data we collect."""
    QUOTE = "quote"
    NEWS = "news"
    FILING = "filing"
    EARNINGS = "earnings"


class TradingSignal(BaseModel):
    """
    Represents a trading signal generated by AI analysis.

    The AI conviction score is a composite of multiple factors:
    - Fundamental analysis (financial statements)
    - Sentiment analysis (news, social media)
    - Technical analysis (price patterns)
    - Earnings call insights
    """
    symbol: str = Field(..., description="Stock ticker symbol")
    signal_type: SignalType = Field(..., description="BUY, SELL, or HOLD")
    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Overall confidence (0-1)"
    )
    ai_conviction_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Composite AI conviction score"
    )
    fundamental_score: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Score from financial statement analysis"
    )
    sentiment_score: Optional[float] = Field(
        default=None,
        ge=-1.0,
        le=1.0,
        description="Sentiment from news/social (-1 to 1)"
    )
    technical_score: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Technical analysis score"
    )
    reasoning: str = Field(..., description="AI explanation for the signal")
    source_agent: str = Field(..., description="Which AI agent generated this")
    metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Additional context"
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        json_schema_extra = {
            "example": {
                "symbol": "AAPL",
                "signal_type": "BUY",
                "confidence_score": 0.85,
                "ai_conviction_score": 0.78,
                "fundamental_score": 0.82,
                "sentiment_score": 0.65,
                "technical_score": 0.75,
                "reasoning": "Strong revenue growth in services segment, positive sentiment from product launch",
                "source_agent": "ensemble_strategy"
            }
        }


class Trade(BaseModel):
    """
    Represents an executed trade with P&L tracking.
    """
    symbol: str
    side: OrderSide
    quantity: int = Field(..., gt=0)
    entry_price: Optional[float] = Field(default=None, gt=0)
    exit_price: Optional[float] = Field(default=None, gt=0)
    pnl: Optional[float] = Field(default=None)
    pnl_percent: Optional[float] = Field(default=None)
    status: OrderStatus = Field(default=OrderStatus.PENDING)
    order_id: Optional[str] = Field(default=None)
    signal_id: Optional[str] = Field(default=None)
    filled_at: Optional[datetime] = Field(default=None)
    closed_at: Optional[datetime] = Field(default=None)
    created_at: datetime = Field(default_factory=datetime.utcnow)

    @validator("pnl", always=True)
    def calculate_pnl(cls, v, values):
        """Automatically calculate P&L if entry and exit prices are available."""
        if v is None and values.get("entry_price") and values.get("exit_price"):
            quantity = values.get("quantity", 0)
            side = values.get("side")
            if side == OrderSide.BUY:
                return (values["exit_price"] - values["entry_price"]) * quantity
            else:  # SELL
                return (values["entry_price"] - values["exit_price"]) * quantity
        return v


class Position(BaseModel):
    """Current portfolio position."""
    symbol: str
    quantity: int
    avg_entry_price: float = Field(..., gt=0)
    current_price: Optional[float] = Field(default=None, gt=0)
    market_value: Optional[float] = Field(default=None)
    unrealized_pnl: Optional[float] = Field(default=None)
    unrealized_pnl_percent: Optional[float] = Field(default=None)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class PortfolioState(BaseModel):
    """Current portfolio state and performance metrics."""
    cash_balance: float
    portfolio_value: float
    total_pnl: float = Field(default=0.0)
    total_pnl_percent: float = Field(default=0.0)
    active_positions: int = Field(default=0)
    win_rate: Optional[float] = Field(default=None, ge=0.0, le=1.0)
    sharpe_ratio: Optional[float] = Field(default=None)
    max_drawdown: Optional[float] = Field(default=None)
    snapshot_at: datetime = Field(default_factory=datetime.utcnow)


class LLMAnalysis(BaseModel):
    """
    Result of LLM analysis on a stock.

    This is cached to reduce API costs.
    """
    symbol: str
    agent_type: str = Field(
        ...,
        description="Type of agent: 'financial', 'sentiment', 'earnings'"
    )
    analysis_result: Dict[str, Any] = Field(
        ...,
        description="Structured analysis output"
    )
    tokens_used: int = Field(default=0, ge=0)
    api_cost: float = Field(default=0.0, ge=0.0, description="Cost in USD")
    processing_time_ms: int = Field(default=0, ge=0)
    cache_hit: bool = Field(default=False)
    created_at: datetime = Field(default_factory=datetime.utcnow)


class MarketNews(BaseModel):
    """News article for sentiment analysis."""
    symbol: str
    headline: str
    summary: Optional[str] = Field(default=None)
    source: str
    url: Optional[str] = Field(default=None)
    published_at: datetime
    sentiment_score: Optional[float] = Field(default=None, ge=-1.0, le=1.0)


class SECFiling(BaseModel):
    """SEC filing data for fundamental analysis."""
    symbol: str
    filing_type: str = Field(..., description="10-K, 10-Q, 8-K, etc.")
    filing_date: datetime
    url: str
    content: Optional[str] = Field(default=None)
    extracted_metrics: Optional[Dict[str, Any]] = Field(default=None)


class EarningsCall(BaseModel):
    """Earnings call transcript for analysis."""
    symbol: str
    quarter: str = Field(..., description="Q1 2024, etc.")
    date: datetime
    transcript: str
    key_insights: Optional[List[str]] = Field(default=None)
    management_tone: Optional[str] = Field(default=None)
